### ISSUE TITLE
BadParcelableException in Parcel.readParcelable()

### ISSUE THREAD

**Issue by LunaSela** [LunaSela/artdawn#6]
<a href="https://github.com/GoogleCodeExporter"><img src="https://avatars.githubusercontent.com/u/9614759?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [GoogleCodeExporter](https://github.com/GoogleCodeExporter)**
_Sun Mar 15 12:39:35 2015_
_Originally opened as https://github.com/balau/fakedawn/issues/11_

----

```
java.lang.RuntimeException: Unable to start activity 
ComponentInfo{org.balau.fakedawn/org.balau.fakedawn.Preferences}: 
android.os.BadParcelableException: ClassNotFoundException when unmarshalling: 
org.balau.fakedawn.IntervalSlider$SavedState
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
at android.app.ActivityThread.access$600(ActivityThread.java:130)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4745)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
at dalvik.system.NativeStart.main(Native Method)
Caused by: android.os.BadParcelableException: ClassNotFoundException when 
unmarshalling: org.balau.fakedawn.IntervalSlider$SavedState
at android.os.Parcel.readParcelable(Parcel.java:2077)
at android.view.AbsSavedState.<init>(AbsSavedState.java:57)
at android.view.View$BaseSavedState.<init>(View.java:17205)
at android.view.View$BaseSavedState$1.createFromParcel(View.java:17220)
at android.view.View$BaseSavedState$1.createFromParcel(View.java:17218)
at android.os.Parcel.readParcelable(Parcel.java:2103)
at android.os.Parcel.readValue(Parcel.java:1965)
at android.os.Parcel.readSparseArrayInternal(Parcel.java:2255)
at android.os.Parcel.readSparseArray(Parcel.java:1687)
at android.os.Parcel.readValue(Parcel.java:2022)
at android.os.Parcel.readMapInternal(Parcel.java:2226)
at android.os.Bundle.unparcel(Bundle.java:223)
at android.os.Bundle.getSparseParcelableArray(Bundle.java:1232)
at 
com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.j
ava:1605)
at android.app.Activity.onRestoreInstanceState(Activity.java:928)
at android.app.Activity.performRestoreInstanceState(Activity.java:900)
at 
android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.j
ava:1130)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2037)
... 11 more


```

Original issue reported on code.google.com by `francesc...@gmail.com` on 4 Oct 2012 at 6:52

**Comment by LunaSela** [comment]
<a href="https://github.com/GoogleCodeExporter"><img src="https://avatars.githubusercontent.com/u/9614759?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GoogleCodeExporter](https://github.com/GoogleCodeExporter)**
_Sun Mar 15 12:39:36 2015_

----

```
Happened when I disabled the alarm and tapped the "Set Alarm" button. The app 
went black and a "Force close" window appeared.

12-27 16:35:41.445 D/FakeDawn(17260)Preferences saved.
12-27 16:35:41.453 D/FakeDawn(17260)Fake Dawn Alarm Disabled.
...
12-27 16:35:41.585 E/RingtoneManager(17260)getRingtone streamType : -1
...
12-27 16:35:41.621 D/FakeDawn(17260)Preferences loaded.
12-27 16:35:41.632 E/Parcel  (17260)Class not found when unmarshalling: 
org.balau.fakedawn.IntervalSlider$SavedState, e: 
java.lang.ClassNotFoundException: org.balau.fakedawn.IntervalSlider$SavedState
12-27 16:35:41.636 W/dalvikvm(17260)threadid=1: thread exiting with uncaught 
exception (group=0x40015578)
12-27 16:35:41.652 E/AndroidRuntime(17260)FATAL EXCEPTION: main
12-27 16:35:41.652 E/AndroidRuntime(17260)java.lang.RuntimeException: Unable to 
start activity 
ComponentInfo{org.balau.fakedawn/org.balau.fakedawn.Preferences}: 
android.os.BadParcelableException: ClassNotFoundException when unmarshalling: 
org.balau.fakedawn.IntervalSlider$SavedState
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1651)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1667)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
android.app.ActivityThread.access$1500(ActivityThread.java:117)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
android.app.ActivityThread$H.handleMessage(ActivityThread.java:935)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
android.os.Handler.dispatchMessage(Handler.java:99)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
android.os.Looper.loop(Looper.java:130)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
android.app.ActivityThread.main(ActivityThread.java:3687)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
java.lang.reflect.Method.invokeNative(Native Method)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
java.lang.reflect.Method.invoke(Method.java:507)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
dalvik.system.NativeStart.main(Native Method)
12-27 16:35:41.652 E/AndroidRuntime(17260)Caused by: 
android.os.BadParcelableException: ClassNotFoundException when unmarshalling: 
org.balau.fakedawn.IntervalSlider$SavedState
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
android.os.Parcel.readParcelable(Parcel.java:1958)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
android.view.AbsSavedState.<init>(AbsSavedState.java:57)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
android.view.View$BaseSavedState.<init>(View.java:9268)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
android.view.View$BaseSavedState$1.createFromParcel(View.java:9283)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
android.view.View$BaseSavedState$1.createFromParcel(View.java:9281)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
android.os.Parcel.readParcelable(Parcel.java:1981)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
android.os.Parcel.readValue(Parcel.java:1846)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
android.os.Parcel.readSparseArrayInternal(Parcel.java:2112)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
android.os.Parcel.readSparseArray(Parcel.java:1568)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
android.os.Parcel.readValue(Parcel.java:1903)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
android.os.Parcel.readMapInternal(Parcel.java:2083)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
android.os.Bundle.unparcel(Bundle.java:208)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
android.os.Bundle.getSparseParcelableArray(Bundle.java:1167)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.j
ava:1525)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
android.app.Activity.onRestoreInstanceState(Activity.java:844)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
android.app.Activity.performRestoreInstanceState(Activity.java:816)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.j
ava:1096)
12-27 16:35:41.652 E/AndroidRuntime(17260)at 
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1629)
12-27 16:35:41.652 E/AndroidRuntime(17260)... 11 more
12-27 16:35:41.679 E/        (137)Dumpstate > /data/log/dumpstate_app_error

```

Original comment by `francesc...@gmail.com` on 27 Dec 2012 at 3:57

**Comment by LunaSela** [comment]
<a href="https://github.com/GoogleCodeExporter"><img src="https://avatars.githubusercontent.com/u/9614759?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GoogleCodeExporter](https://github.com/GoogleCodeExporter)**
_Sun Mar 15 12:39:36 2015_

----

```
Last reported
Jul 23, 2013
Application version
1.2
Reports this week
1
Reports total
1
java.lang.RuntimeException: Unable to start activity 
ComponentInfo{org.balau.fakedawn/org.balau.fakedawn.Preferences}: 
android.os.BadParcelableException: ClassNotFoundException when unmarshalling: 
org.balau.fakedawn.IntervalSlider$SavedState
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
at android.app.ActivityThread.access$600(ActivityThread.java:141)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5041)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
at dalvik.system.NativeStart.main(Native Method)
Caused by: android.os.BadParcelableException: ClassNotFoundException when 
unmarshalling: org.balau.fakedawn.IntervalSlider$SavedState
at android.os.Parcel.readParcelable(Parcel.java:2077)
at android.view.AbsSavedState.<init>(AbsSavedState.java:57)
at android.view.View$BaseSavedState.<init>(View.java:17594)
at android.view.View$BaseSavedState$1.createFromParcel(View.java:17609)
at android.view.View$BaseSavedState$1.createFromParcel(View.java:17607)
at android.os.Parcel.readParcelable(Parcel.java:2103)
at android.os.Parcel.readValue(Parcel.java:1965)
at android.os.Parcel.readSparseArrayInternal(Parcel.java:2255)
at android.os.Parcel.readSparseArray(Parcel.java:1687)
at android.os.Parcel.readValue(Parcel.java:2022)
at android.os.Parcel.readMapInternal(Parcel.java:2226)
at android.os.Bundle.unparcel(Bundle.java:223)
at android.os.Bundle.getSparseParcelableArray(Bundle.java:1240)
at 
com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.j
ava:1631)
at android.app.Activity.onRestoreInstanceState(Activity.java:938)
at android.app.Activity.performRestoreInstanceState(Activity.java:910)
at 
android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.j
ava:1131)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2158)
... 11 more
```

Original comment by `francesc...@gmail.com` on 26 Jul 2013 at 6:16

**Comment by LunaSela** [comment]
<a href="https://github.com/GoogleCodeExporter"><img src="https://avatars.githubusercontent.com/u/9614759?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GoogleCodeExporter](https://github.com/GoogleCodeExporter)**
_Sun Mar 15 12:39:36 2015_

----

```
Should be mitigated/completely fixed by ra00d7bcb89ec and r3b1ab2db8533
```

Original comment by `francesc...@gmail.com` on 5 Oct 2014 at 7:10
* Changed state: **Fixed**

**Comment by LunaSela** [comment]
<a href="https://github.com/GoogleCodeExporter"><img src="https://avatars.githubusercontent.com/u/9614759?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [GoogleCodeExporter](https://github.com/GoogleCodeExporter)**
_Sun Mar 15 12:39:36 2015_

----

```
Another crash report came in, reopening the issue.

Application version 1.3
Android version Android 4.4
Device Nexus 7 (2012) (tilapia)

java.lang.RuntimeException: Unable to start activity 
ComponentInfo{org.balau.fakedawn/org.balau.fakedawn.Preferences}: 
android.os.BadParcelableException: ClassNotFoundException when unmarshalling: 
org.balau.fakedawn.IntervalSlider$SavedState
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
at android.app.ActivityThread.access$800(ActivityThread.java:135)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5001)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at 
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
at dalvik.system.NativeStart.main(Native Method)
Caused by: android.os.BadParcelableException: ClassNotFoundException when 
unmarshalling: org.balau.fakedawn.IntervalSlider$SavedState
at android.os.Parcel.readParcelableCreator(Parcel.java:2147)
at android.os.Parcel.readParcelable(Parcel.java:2097)
at android.view.AbsSavedState.<init>(AbsSavedState.java:57)
at android.view.View$BaseSavedState.<init>(View.java:18661)
at org.balau.fakedawn.TimeSlider$SavedState.<init>(TimeSlider.java:329)
at 
org.balau.fakedawn.TimeSlider$SavedState$1.createFromParcel(TimeSlider.java:352)
at 
org.balau.fakedawn.TimeSlider$SavedState$1.createFromParcel(TimeSlider.java:1)
at android.os.Parcel.readParcelable(Parcel.java:2104)
at android.os.Parcel.readValue(Parcel.java:2013)
at android.os.Parcel.readSparseArrayInternal(Parcel.java:2363)
at android.os.Parcel.readSparseArray(Parcel.java:1735)
at android.os.Parcel.readValue(Parcel.java:2070)
at android.os.Parcel.readArrayMapInternal(Parcel.java:2314)
at android.os.Bundle.unparcel(Bundle.java:249)
at android.os.Bundle.getSparseParcelableArray(Bundle.java:1273)
at 
com.android.internal.policy.impl.PhoneWindow.restoreHierarchyState(PhoneWindow.j
ava:1741)
at android.app.Activity.onRestoreInstanceState(Activity.java:944)
at android.app.Activity.performRestoreInstanceState(Activity.java:916)
at 
android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.j
ava:1138)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)
... 11 more
```

Original comment by `francesc...@gmail.com` on 13 Dec 2014 at 2:24
* Changed state: **New**

**Comment by LunaSela** [comment]
Should be fixed as the slider component got replaced.
